# Generated by Django 4.2.21 on 2025-06-03 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('age_limit', models.CharField(max_length=100, null=True)),
                ('movie_type', models.CharField(max_length=100, null=True)),
                ('format', models.CharField(max_length=100, null=True)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('image_url', models.TextField()),
                ('booking_url', models.TextField()),
                ('price', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'films',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Screentime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('date', models.DateTimeField()),
                ('language', models.CharField(max_length=100)),
                ('firstclass', models.CharField(max_length=10)),
                ('cinema_id', models.CharField(max_length=30, null=True)),
                ('film_id', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'screentimes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50)),
                ('cinema_id', models.CharField(max_length=30)),
                ('cinema_name', models.CharField(max_length=200)),
                ('movie_title', models.CharField(max_length=200)),
                ('movie_format', models.CharField(max_length=20)),
                ('movie_language', models.CharField(max_length=50)),
                ('movie_label', models.CharField(max_length=10)),
                ('showtime', models.DateTimeField()),
                ('screen_name', models.CharField(max_length=50)),
                ('screen_number', models.IntegerField()),
                ('seats_available', models.IntegerField()),
                ('expire_time', models.DateTimeField()),
                ('tickets_data', models.JSONField()),
                ('seats_layout', models.JSONField()),
                ('concession_items', models.JSONField()),
                ('standard_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vip_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('couple_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('search_date', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'seat_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('theater_id', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cinemas',
                'managed': False,
            },
        ),
    ]
