# Generated by Django 4.2.21 on 2025-06-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_usershowing'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usershowing',
            table=None,
        ),
    ]
